In [1]:
import pandas as pd

In [2]:
data = {
    'Name': ['Amit','Neha','Ravi','Sita'],
    'Age':[21,22,None,20],
    'Marks':[85,30,78,88]
}
df=pd.DataFrame(data)
df

   Name   Age  Marks
0  Amit  21.0     85
1  Neha  22.0     30
2  Ravi   NaN     78
3  Sita  20.0     88

In [3]:
df['Grade']=['B','A','C','D']
df

   Name   Age  Marks Grade
0  Amit  21.0     85     B
1  Neha  22.0     30     A
2  Ravi   NaN     78     C
3  Sita  20.0     88     D

In [4]:
df[['Name','Marks']]

   Name  Marks
0  Amit     85
1  Neha     30
2  Ravi     78
3  Sita     88

In [5]:
df.isnull().sum()

Name     0
Age      1
Marks    0
Grade    0
dtype: int64

In [6]:
df['Age'].fillna(df['Age'].mean(),inplace=True)
df

C:\Users\User\AppData\Local\Temp\ipykernel_6724\2368695939.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Age'].fillna(df['Age'].mean(),inplace=True)

   Name   Age  Marks Grade
0  Amit  21.0     85     B
1  Neha  22.0     30     A
2  Ravi   NaN     78     C
3  Sita  20.0     88     D

In [7]:
df['Age']=df['Age'].fillna(df['Age'].mean())
df

   Name   Age  Marks Grade
0  Amit  21.0     85     B
1  Neha  22.0     30     A
2  Ravi  21.0     78     C
3  Sita  20.0     88     D

In [8]:
df.loc[2,'Name']='Sonu'
df

   Name   Age  Marks Grade
0  Amit  21.0     85     B
1  Neha  22.0     30     A
2  Sonu  21.0     78     C
3  Sita  20.0     88     D

In [11]:
new_rows = pd.DataFrame([
    {'Name': 'Kumar', 'Age': 20, 'Marks': 90, 'Grade': 'A'},
    {'Name': 'Rahul', 'Age': 26, 'Marks': 85, 'Grade': 'B'}
])

In [12]:
df = pd.concat([df, new_rows], ignore_index=True)
df

    Name   Age  Marks Grade
0   Amit  21.0     85     B
1   Neha  22.0     30     A
2   Sonu  21.0     78     C
3   Sita  20.0     88     D
4  Kumar  20.0     90     A
5  Rahul  26.0     85     B

In [14]:
df.loc[0, ['Name', 'Marks']]

Name     Amit
Marks      85
Name: 0, dtype: object

In [15]:
df.loc[0:3, ['Name', 'Marks']]

   Name  Marks
0  Amit     85
1  Neha     30
2  Sonu     78
3  Sita     88

In [16]:
df.iloc[0:3:2, 0:2]

   Name   Age
0  Amit  21.0
2  Sonu  21.0

In [17]:
print("Mean Age:", df['Age'].mean()) 
print("Min Age:", df['Age'].min())    
print("Max Age:", df['Age'].max())    
print("Count Age:", df['Age'].count())

Mean Age: 21.666666666666668
Min Age: 20.0
Max Age: 26.0
Count Age: 6

In [18]:
df.groupby('Name')['Age'].mean()

Name
Amit     21.0
Kumar    20.0
Neha     22.0
Rahul    26.0
Sita     20.0
Sonu     21.0
Name: Age, dtype: float64

In [19]:
df.sort_values(by='Marks', ascending=False).head(3)

    Name   Age  Marks Grade
4  Kumar  20.0     90     A
3   Sita  20.0     88     D
0   Amit  21.0     85     B